//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citrullia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class ScoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ScoreSettings defaultInstance = ((ScoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ScoreSettings())));
        
        public static ScoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double CutOffScore {
            get {
                return ((double)(this["CutOffScore"]));
            }
            set {
                this["CutOffScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeCutOff {
            get {
                return ((bool)(this["IncludeCutOff"]));
            }
            set {
                this["IncludeCutOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AIonMatchScore {
            get {
                return ((int)(this["AIonMatchScore"]));
            }
            set {
                this["AIonMatchScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BIonMatchScore {
            get {
                return ((int)(this["BIonMatchScore"]));
            }
            set {
                this["BIonMatchScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int YIonMatchScore {
            get {
                return ((int)(this["YIonMatchScore"]));
            }
            set {
                this["YIonMatchScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int IonLossMatchScoreDivider {
            get {
                return ((int)(this["IonLossMatchScoreDivider"]));
            }
            set {
                this["IonLossMatchScoreDivider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MS1CyanicLossScore {
            get {
                return ((int)(this["MS1CyanicLossScore"]));
            }
            set {
                this["MS1CyanicLossScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MS2CyanicAIon {
            get {
                return ((int)(this["MS2CyanicAIon"]));
            }
            set {
                this["MS2CyanicAIon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MS2CyanicBIon {
            get {
                return ((int)(this["MS2CyanicBIon"]));
            }
            set {
                this["MS2CyanicBIon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MS2CyanicYIon {
            get {
                return ((int)(this["MS2CyanicYIon"]));
            }
            set {
                this["MS2CyanicYIon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MS2CyanicNeuLoss {
            get {
                return ((int)(this["MS2CyanicNeuLoss"]));
            }
            set {
                this["MS2CyanicNeuLoss"] = value;
            }
        }
    }
}
